export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const GET_SPECIFIC_CATEGORY = 'GET_SPECIFIC_CATEGORY';

export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const GET_SPECIFIC_PRODUCT = 'GET_SPECIFIC_PRODUCT';
export const GET_PRODUCTS_FOR_CATEGORY = 'GET_PRODUCTS_FOR_CATEGORY';

export const CREATE_USER = 'CREATE_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const UPDATE_USER = 'UPDATE_USER';

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const DELETE_FROM_WISHLIST = 'DELETE_FROM_WISHLIST';
export const GET_USER_WISHLIST = 'GET_USER_WISHLIST';

export const CREATE_CART = 'CREATE_CART';
export const GET_ALL_CART = 'GET_ALL_CART';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const GET_TOTAL_PRICE = 'GET_TOTAL_PRICE';

export const ADD_ORDER_ITEMS = 'ADD_ORDER_ITEMS';
export const ALL_ORDERS_ITEMS = 'ALL_ORDERS_ITEMS';
export const GET_SPECIFIC_ORDER_ITEMS = 'GET_SPECIFIC_ORDER_ITEMS';
export const DELETE_ORDER_ITEMS = 'DELETE_ORDER_ITEMS';

export const ADD_ORDER = 'ADD_ORDER';
export const ALL_ORDERS = 'ALL_ORDERS';
export const GET_SPECIFIC_ORDER = 'GET_SPECIFIC_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';

export const CATCH_ERROR = 'CATCH_ERROR';
